# Generated by Django 4.2.9 on 2024-01-29 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('source', models.TextField()),
                ('published', models.DateTimeField()),
                ('added', models.DateTimeField()),
                ('url', models.URLField()),
                ('region', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=100)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
                ('relevance', models.IntegerField()),
                ('intensity', models.IntegerField()),
                ('likelihood', models.IntegerField()),
                ('pestle', models.CharField(max_length=100)),
                ('insight', models.CharField(max_length=100)),
                ('impact', models.TextField()),
            ],
        ),
    ]
